#ifndef __COLOR_H__
#define __COLOR_H__

extern int LightPink[];	        //浅粉红	#FFB6C1	
extern int Pink[];	            //粉红	    #FFC0CB	
extern int Crimson[];           //猩红	    #DC143C	
extern int LavenderBlush[];	    //脸红的淡紫色	    #FFF0F5	
extern int PaleVioletRed[];	    //苍白的紫罗兰红色	#DB7093	
extern int HotPink[];	        //热情的粉红	    #FF69B4	
extern int DeepPink[];	        //深粉色	        #FF1493	
extern int MediumVioletRed[];	//适中的紫罗兰红色	#C71585	
extern int Orchid[];	        //兰花的紫色	    #DA70D6	
extern int Thistle[];	        //蓟	    #D8BFD8	
extern int plum[];	            //李子	    #DDA0DD	
extern int Violet[];	        //紫罗兰	#EE82EE	
extern int Magenta[];	        //洋红	    #FF00FF	
extern int Fuchsia[];	        //灯笼海棠(紫红色)	#FF00FF	
extern int DarkMagenta[];	    //深洋红色	        #8B008B	
extern int Purple[];	        //紫色	            #800080	
extern int MediumOrchid[];	    //适中的兰花紫	#BA55D3	
extern int DarkVoilet[];	    //深紫罗兰色	#9400D3	
extern int DarkOrchid[];	    //深兰花紫	    #9932CC	
extern int Indigo[];	        //靛青	        #4B0082	
extern int BlueViolet[];	    //深紫罗兰的蓝色	    #8A2BE2	
extern int MediumPurple[];	    //适中的紫色	        #9370DB	
extern int MediumSlateBlue[];	//适中的板岩暗蓝灰色	#7B68EE	
extern int SlateBlue[];	        //板岩暗蓝灰色	    #6A5ACD	
extern int DarkSlateBlue[];	    //深岩暗蓝灰色	    #483D8B	
extern int Lavender[];     	    //熏衣草花的淡紫色	#E6E6FA	
extern int GhostWhite[];	    //幽灵的白色	    #F8F8FF	
extern int Blue[];   	        //纯蓝	            #0000FF	
extern int MediumBlue[];	    //适中的蓝色	    #0000CD	
extern int MidnightBlue[];	    //午夜的蓝色	    #191970	
extern int DarkBlue[];	        //深蓝色	    #00008B	
extern int Navy[];	            //海军蓝	    #000080	
extern int RoyalBlue[];	        //皇家蓝	    #4169E1	
extern int CornflowerBlue[];	//矢车菊的蓝色	#6495ED	
extern int LightSteelBlue[];	//淡钢蓝	    #B0C4DE	
extern int LightSlateGray[];	//浅石板灰	    #778899	
extern int SlateGray[];	    //石板灰	#708090	
extern int DoderBlue[];	    //道奇蓝	#1E90FF	
extern int AliceBlue[];     //爱丽丝蓝	#F0F8FF	
extern int SteelBlue[];	    //钢蓝	    #4682B4	
extern int LightSkyBlue[];	//淡蓝色	#87CEFA	
extern int SkyBlue[];	    //天蓝色	#87CEEB	
extern int DeepSkyBlue[];	//深天蓝	#00BFFF	
extern int LightBLue[];	    //淡蓝	    #ADD8E6	
extern int PowDerBlue[];	//火药蓝	#B0E0E6	
extern int CadetBlue[];     //军校蓝	#5F9EA0	
extern int Azure[];	        //蔚蓝色	#F0FFFF	
extern int LightCyan[];	    //淡青色	#E1FFFF	
extern int PaleTurquoise[]; //苍白的绿宝石	#AFEEEE	
extern int Cyan[];	        //青色	        #00FFFF	
extern int Aqua[];	        //水绿色	#00FFFF	
extern int DarkTurquoise[];	//深绿宝石	#00CED1	
extern int DarkSlateGray[];	//深石板灰	#2F4F4F	
extern int DarkCyan[];	    //深青色	#008B8B	
extern int Teal[];	        //水鸭色	#008080	
extern int MediumTurquoise[];	//适中的绿宝石	#48D1CC	
extern int LightSeaGreen[];	    //浅海洋绿	    #20B2AA	
extern int Turquoise[];	        //绿宝石	    #40E0D0	
extern int Auqamarin[];	        //绿玉\碧绿色	#7FFFAA	
extern int MediumAquamarine[];	//适中的碧绿色	    #00FA9A	
extern int MediumSpringGreen[];	//适中的春天的绿色	#00FF7F	
extern int MintCream[];     //薄荷奶油	            #F5FFFA	
extern int SpringGreen[];   //春天的绿色	        #3CB371	
extern int SeaGreen[];	    //海洋绿	    #2E8B57	
extern int Honeydew[];	    //蜂蜜	        #F0FFF0	
extern int LightGreen[];    //淡绿色	    #90EE90	
extern int PaleGreen[];	    //苍白的绿色	#98FB98	
extern int DarkSeaGreen[];	//深海洋绿	#8FBC8F	
extern int LimeGreen[];	    //酸橙绿	#32CD32	
extern int Lime[];	        //酸橙色	#00FF00	
extern int ForestGreen[];   //森林绿	#228B22	
extern int Green[];         //纯绿	    #008000	
extern int DarkGreen[];     //深绿色	#006400	
extern int inttreuse[];	    //查特酒绿	#7FFF00	
extern int LawnGreen[];	    //草坪绿	#7CFC00	
extern int GreenYellow[];   //绿黄色	#ADFF2F	
extern int OliveDrab[];	    //橄榄土褐色	        #556B2F	
extern int Beige[];         //米色(浅褐色)	        #F5F5DC	
extern int LightGoldenrodYellow[];	//浅秋麒麟黄	#FAFAD2	
extern int Ivory[];	        //象牙	    #FFFFF0	
extern int LightYellow[];   //浅黄色	#FFFFE0	
extern int Yellow[];	    //纯黄	    #FFFF00	
extern int Olive[];	        //橄榄	    #808000	
extern int DarkKhaki[];	    //深卡其布	#BDB76B	
extern int LemonChiffon[];	//柠檬薄纱	#FFFACD	
extern int PaleGodenrod[];	//灰秋麒麟	#EEE8AA	
extern int Khaki[];	        //卡其布	#F0E68C	
extern int Gold[];	        //金	    #FFD700	
extern int Cornislk[];	    //玉米色	#FFF8DC	
extern int GoldEnrod[];	    //秋麒麟	#DAA520	
extern int FloralWhite[];	   //花的白色	#FFFAF0	
extern int OldLace[];	       //老饰带	    #FDF5E6	
extern int Wheat[];	           //小麦色	    #F5DEB3	
extern int Moccasin[];	       //鹿皮鞋	    #FFE4B5	
extern int Orange[];	       //橙色	    #FFA500	
extern int PapayaWhip[];	   //番木瓜	    #FFEFD5	
extern int BlanchedAlmond[];   //漂白的杏仁	#FFEBCD	
extern int NavajoWhite[];	//纳瓦霍白	    #FFDEAD	
extern int AntiqueWhite[];	//古代的白色	#FAEBD7	
extern int Tan[];	        //晒黑	        #D2B48C	
extern int BrulyWood[];   	//结实的树	    #DEB887	
extern int Bisque[];	    //(浓汤)乳脂,番茄等	#FFE4C4	
extern int DarkOrange[];    //深橙色	#FF8C00	
extern int Linen[];	        //亚麻布	#FAF0E6	
extern int Peru[];	        //秘鲁	    #CD853F	
extern int PeachPuff[];	    //桃色	    #FFDAB9	
extern int SandyBrown[];    //沙棕色	#F4A460	
extern int Chocolate[];	    //巧克力	#D2691E	
extern int SaddleBrown[];   //马鞍棕色	#8B4513	
extern int SeaShell[];	    //海贝壳	#FFF5EE	
extern int Sienna[];	    //黄土赭色	#A0522D	
extern int LightSalmon[];	//浅鲜肉(鲑鱼)色	#FFA07A	
extern int Coral[];	        //珊瑚	            #FF7F50	
extern int OrangeRed[];	    //橙红色	        #FF4500	
extern int DarkSalmon[];	//深鲜肉(鲑鱼)色	#E9967A	
extern int Tomato[];	    //番茄	            #FF6347	
extern int MistyRose[];	    //薄雾玫瑰	        #FFE4E1	
extern int Salmon[];	    //鲜肉(鲑鱼)色	    #FA8072	
extern int Snow[];	        //雪	            #FFFAFA	
extern int LightCoral[];	//淡珊瑚色	#F08080	
extern int RosyBrown[];	    //玫瑰棕色	#BC8F8F	
extern int IndianRed[];	    //印度红	#CD5C5C	
extern int Red[];	        //纯红	    #FF0000	
extern int Brown[];	        //棕色	    #A52A2A	
extern int FireBrick[];	    //耐火砖	#B22222	
extern int DarkRed[];	    //深红色	#8B0000	
extern int Maroon[];	    //栗色	    #800000	
extern int White[];	        //纯白	    #FFFFFF	
extern int WhiteSmoke[];    //白烟	    #F5F5F5	
extern int Gainsboro[];	    //亮灰色	#DCDCDC	
extern int LightGrey[];	    //浅灰色	#D3D3D3	
extern int Silver[];	    //银白色	#C0C0C0	
extern int DarkGray[];	    //深灰色	#A9A9A9	
extern int Gray[];	        //灰色	    #808080	
extern int DimGray[];	    //暗淡的灰色	#696969	
extern int Black[];	        //纯黑	        #000000	


#endif

